name: Compile and Commit Typst Files
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Compile Typst to PDF
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: 'src/calculus.typ src/quadratics.typ src/korean_calculus.typ'
          output_paths: 'outputs/calculus.pdf outputs/quadratics.pdf outputs/korean_calculus.pdf'
          fonts_path: 'fonts'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: '**/*.pdf'

      - name: Release on tag
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag' # Corrected this line
        with:
          name: "${{ github.ref_name }}"
          files: |
            outputs/calculus.pdf # Assuming these are the correct paths after compilation
            outputs/quadratics.pdf
            outputs/korean_calculus.pdf
